---
- name: get the correct kernel-devel version from running kernel
  shell: echo kernel-devel-`uname -r`
  register: kernel_version

- name: try to install the same kernel-devel version as running kernel
  yum:
    name: "{{ kernel_version.stdout }}"

- name: Install epel/cuda repo from a remote rpm
  yum:
    name:  https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Install NVIDIA repo from a remote rpm
  yum:
    name: https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/cuda-repo-rhel7-9.1.85-1.x86_64.rpm
    state: present

- name: Install xorg-x11-drv-nvidia
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - xorg-x11-drv-nvidia
    - xorg-x11-drv-nvidia-devel
    - clinfo

- name: add NVIDIA container repos
  yum_repository:
    name:          "{{ item.name }}"
    description:   NVIDIA container (docker) YUM repo
    file:          "{{ item.name }}"
    baseurl:       https://nvidia.github.io/{{ item.name }}/centos7/x86_64
    repo_gpgcheck: yes
    gpgcheck:      no
    gpgkey:        https://nvidia.github.io/{{ item.name }}/gpgkey
    sslverify:     yes
    sslcacert:     /etc/pki/tls/certs/ca-bundle.crt
  with_items:
    - { name: 'libnvidia-container' }
    - { name: 'nvidia-container-runtime' }

- name: import rpm keys
  rpm_key:
    state=present
    key={{ item }}
  with_items:
    - https://nvidia.github.io/nvidia-container-runtime/gpgkey
    - https://nvidia.github.io/libnvidia-container/gpgkey

- name: update repo cache for the new repo
  command: yum -q makecache -y --disablerepo=* --enablerepo={{ item }}
  with_items:
    - libnvidia-container
    - nvidia-container-runtime

- name: install nvidia-container-runtime
  yum:
    name: nvidia-container-runtime-1.1.1-1.docker1.13.1.x86_64
    state: present
    update_cache: yes

- name: change selinux context of nvidia files
  shell: |
    chcon -t container_file_t  /dev/nvidia*
    chcon -t container_file_t  /usr/lib64/nvidia/libnvidia*
    chcon -t container_file_t  /usr/bin/nvidia-*


